const fs = require('fs');
const core = require('@actions/core');
const github = require('@actions/github');

// ---------------------------------------------------------------------------
// 1. The checklist
// Each check has: a stable id (used for skip-checks), a display name,
// a weight (all weights should sum to 100), and a check() function that
// returns true/false based on the filesystem.
// ---------------------------------------------------------------------------
const CHECKS = [
  {
    id: 'readme',
    name: 'README exists',
    weight: 15,
    check: () => fs.existsSync('README.md') || fs.existsSync('readme.md'),
  },
  {
    id: 'license',
    name: 'License found',
    weight: 15,
    check: () =>
      fs.existsSync('LICENSE') ||
      fs.existsSync('LICENSE.md') ||
      fs.existsSync('LICENSE.txt'),
  },
  {
    id: 'tests',
    name: 'Tests detected',
    weight: 15,
    check: () =>
      fs.existsSync('test') ||
      fs.existsSync('tests') ||
      fs.existsSync('__tests__') ||
      fs.existsSync('spec'),
  },
  {
    id: 'contributing',
    name: 'CONTRIBUTING.md exists',
    weight: 10,
    check: () => fs.existsSync('CONTRIBUTING.md'),
  },
  {
    id: 'code-of-conduct',
    name: 'Code of Conduct exists',
    weight: 10,
    check: () => fs.existsSync('CODE_OF_CONDUCT.md'),
  },
  {
    id: 'actions-configured',
    name: 'GitHub Actions configured',
    weight: 15,
    check: () =>
      fs.existsSync('.github/workflows') &&
      fs.readdirSync('.github/workflows').length > 0,
  },
  {
    id: 'security-policy',
    name: 'Security Policy exists',
    weight: 10,
    check: () => fs.existsSync('SECURITY.md') || fs.existsSync('.github/SECURITY.md'),
  },
  {
    id: 'dependabot',
    name: 'Dependabot enabled',
    weight: 10,
    check: () => fs.existsSync('.github/dependabot.yml') || fs.existsSync('.github/dependabot.yaml'),
  },
];

// ---------------------------------------------------------------------------
// 2. Run the checklist (respecting skip-checks) and compute the score
// ---------------------------------------------------------------------------
function runChecks(skipIds) {
  const activeChecks = CHECKS.filter((c) => !skipIds.includes(c.id));

  const results = activeChecks.map((c) => {
    let passed = false;
    try {
      passed = !!c.check();
    } catch (err) {
      // A check throwing (e.g. permission error) counts as failed, not fatal
      passed = false;
    }
    return { ...c, passed };
  });

  const totalWeight = results.reduce((sum, r) => sum + r.weight, 0);
  const earnedWeight = results
    .filter((r) => r.passed)
    .reduce((sum, r) => sum + r.weight, 0);

  const score = totalWeight === 0 ? 0 : Math.round((earnedWeight / totalWeight) * 100);
  const passedCount = results.filter((r) => r.passed).length;

  return { results, score, passedCount, totalCount: results.length };
}

// ---------------------------------------------------------------------------
// 3. Build the markdown report (shared by PR comment + job summary)
// ---------------------------------------------------------------------------
function buildReportMarkdown({ results, score }) {
  const lines = [];
  lines.push(`## Project Health Score: ${score}/100`);
  lines.push('');
  for (const r of results) {
    lines.push(`${r.passed ? '✅' : '❌'} ${r.name}`);
  }
  lines.push('');
  lines.push('_Generated by [Project Health Score](https://github.com/marketplace/actions/project-health-score)_');
  return lines.join('\n');
}

// A unique marker lets us find-and-update our own previous comment instead of
// spamming a new comment on every push to the same PR.
const COMMENT_MARKER = '<!-- project-health-score-comment -->';

// ---------------------------------------------------------------------------
// 4. Post (or update) the PR comment
// ---------------------------------------------------------------------------
async function postOrUpdateComment(octokit, context, body) {
  const pr = context.payload.pull_request;
  if (!pr) {
    core.info('Not a pull_request event — skipping PR comment.');
    return;
  }

  const { owner, repo } = context.repo;
  const issue_number = pr.number;
  const fullBody = `${COMMENT_MARKER}\n${body}`;

  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number,
  });

  const existing = comments.find((c) => c.body && c.body.includes(COMMENT_MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body: fullBody,
    });
    core.info(`Updated existing comment (id: ${existing.id}).`);
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number,
      body: fullBody,
    });
    core.info('Created new PR comment.');
  }
}

// ---------------------------------------------------------------------------
// 5. Main entry point
// ---------------------------------------------------------------------------
async function run() {
  try {
    const token = core.getInput('github-token', { required: true });
    const skipInput = core.getInput('skip-checks');
    const shouldPostComment = core.getInput('post-comment') !== 'false';

    const skipIds = skipInput
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);

    const { results, score, passedCount, totalCount } = runChecks(skipIds);
    const report = buildReportMarkdown({ results, score });

    // Log to the console too, so it's visible in the workflow run log
    core.info(report.replace(/\n/g, '\n'));

    if (shouldPostComment) {
      const octokit = github.getOctokit(token);
      await postOrUpdateComment(octokit, github.context, report);
    }

    // Job summary — shows up on the Actions run page itself
    await core.summary
      .addHeading(`Project Health Score: ${score}/100`)
      .addTable([
        [
          { data: 'Check', header: true },
          { data: 'Status', header: true },
        ],
        ...results.map((r) => [r.name, r.passed ? '✅ Passed' : '❌ Missing']),
      ])
      .write();

    core.setOutput('score', score);
    core.setOutput('passed-count', passedCount);
    core.setOutput('total-count', totalCount);
  } catch (error) {
    core.setFailed(error.message);
  }
}

// Only auto-run when this file is executed directly by the Actions runner
// (via dist/index.js). When required by tests, calling run() would try to
// call core.getInput()/GitHub APIs outside of an Actions environment and fail.
if (require.main === module) {
  run();
}

module.exports = { runChecks, buildReportMarkdown, CHECKS, run };
